const quotes = [
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Life is what happens when you're busy making other plans. – John Lennon",
    "Get busy living or get busy dying. – Stephen King",
    "You have within you right now, everything you need to deal with whatever the world can throw at you. – Brian Tracy",
    "The best way to predict the future is to create it. – Peter Drucker",
    "Life is short, and it's up to you to make it sweet. – Sarah Louise Delany",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. – Ralph Waldo Emerson",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "The purpose of our lives is to be happy. – Dalai Lama",
    "You only live once, but if you do it right, once is enough. – Mae West",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. – Martin Luther King Jr.",
    "The only impossible journey is the one you never begin. – Tony Robbins",
    "To be great is to be misunderstood. – Ralph Waldo Emerson",
    "You must be the change you wish to see in the world. – Mahatma Gandhi",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "The best revenge is massive success. – Frank Sinatra",
    "In three words I can sum up everything I've learned about life: it goes on. – Robert Frost",
    "You miss 100% of the shots you don't take. – Wayne Gretzky",
    "The journey of a thousand miles begins with one step. – Lao Tzu",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "Act as if what you do makes a difference. It does. – William James",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "To live is the rarest thing in the world. Most people exist, that is all. – Oscar Wilde",
    "We don't see things as they are, we see them as we are. – Anaïs Nin",
    "To handle yourself, use your head; to handle others, use your heart. – Eleanor Roosevelt",
    "The most wasted of days is one without laughter. – E.E. Cummings",
    "In the middle of difficulty lies opportunity. – Albert Einstein",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
    "Happiness is not something ready-made. It comes from your own actions. – Dalai Lama",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "It does not do to dwell on dreams and forget to live. – J.K. Rowling",
    "To love and be loved is to feel the sun from both sides. – David Viscott",
    "Everything you’ve ever wanted is on the other side of fear. – George Addair",
    "Life isn't about finding yourself. Life is about creating yourself. – George Bernard Shaw",
    "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
    "The best way to find yourself is to lose yourself in the service of others. – Mahatma Gandhi",
    "Life is really simple, but we insist on making it complicated. – Confucius",
    "The only true wisdom is in knowing you know nothing. – Socrates",
    "We may encounter many defeats but we must not be defeated. – Maya Angelou",
    "Everything has beauty, but not everyone can see. – Confucius",
    "The mind is everything. What you think you become. – Buddha",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "Do what you can, with what you have, where you are. – Theodore Roosevelt",
    "Your time is limited, don’t waste it living someone else’s life. – Steve Jobs",
    "The only person you should try to be better than is the person you were yesterday. – Anonymous",
    "Success is going from failure to failure without losing your enthusiasm. – Winston S. Churchill",
    "The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb",
    "The harder you work for something, the greater you'll feel when you achieve it. – Anonymous",
    "Dream bigger. Do bigger. – Anonymous",
    "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
    "The secret of getting ahead is getting started. – Mark Twain",
    "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
    "If you want to lift yourself up, lift up someone else. – Booker T. Washington",
    "Opportunities don't happen. You create them. – Chris Grosser",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. – Christian D. Larson"
];
const genrate = document.getElementById('quote');
console.log(quotes.length);
genrate.onclick = ()=>{
    

    document.getElementById('quote-of-day').innerHTML=quotes[Math.floor(Math.random(quotes)*quotes.length)];

};